# Generated by Django 2.1.1 on 2019-05-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20190522_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='serivce',
            new_name='service',
        ),
    ]
